apiVersion: v1
name: orchestrator
version: 0.1.2
appVersion: 3.0.11
description: A Helm chart for github's mysql orchestrator
keywords:
  - mysql
  - percona
  - orchestrator
home: https://github.com/github/orchestrator
sources:
  - https://github.com/github/orchestrator.git
icon: https://github.com/github/orchestrator/raw/master/resources/public/images/orchestrator-logo-32.png
